site_name: TaskSupervisor
site_description: Assigning Transport Orders to AGVs
docs_dir: docs/
site_dir: html
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs


markdown_extensions:
    - toc:
          baselevel: 2
    - fenced_code
    - attr_list

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - bash
        - yml

nav:
    - Home: index.md
    - Getting Started: start.md
    - User Manual: 
        - Introduction: user/introduction.md
        - Architecture: user/architecture.md
        - Docker: user/docker.md
        - Known Limitations: user/known-limitations.md
    - Installation & Administration:
        - Introduction: install/introduction.md
        - Installation: install/install.md
        - Configuration: install/configuration.md
        - Logs: install/logs.md
    - Programmers Manual:
        - Integrate your Broker: programmers/integrate-your-broker.md
        - Connecting to Middlewares: programmers/connecting-to-middlewares.md
        - Interfaces: programmers/interfaces.md
        - Materialflow: programmers/materialflow.md
        - Entities: programmers/entities.md
    - Examples:
        - Introduction: examples/introduction.md
        - Materialflows:
            - TransportOrderGoodsPallet: examples/materialflows/transportorder-goodspallet.md
            - TransportOrderGoodsPallet Forever: examples/materialflows/transportorder-goodspallet-forever.md
            - TransportOrderGoodsPallet TriggeredBy: examples/materialflows/transportorder-goodspallet-triggeredby.md
            - TransportOrderGoodsPallet FinishedBy: examples/materialflows/transportorder-goodspallet-finishedby.md
            - TransportOrderGoodsPallet OnDone: examples/materialflows/transportorder-goodspallet-ondone.md
            - TransportOrderGoodsPallet Parallel: examples/materialflows/transportorder-goodspallet-parallel.md
            - TransportOrderGoodsPallet Invalid: examples/materialflows/transportorder-goodspallet-invalid.md
    - Glossary: glossary.md
    - Usage: usage.md
    - Deprecated Functionality: deprecated.md
