site_name: TaskSupervisor
site_description: Assigning Transport Orders to AGVs
docs_dir: docs/
site_dir: html
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs

nav:
    - Home: index.md
    - Getting Started: start.md
    - User Manual: 
        - Introduction: user/introduction.md
        - Architecture: user/architecture.md
        - Docker: user/docker.md
        - Known Limitations: user/known-limitatins.md
    - Installation & Administration:
        - Introduction: install/introduction.md
        - Installation: install/install.md
        - Configuration: install/configuration.md
        - Logs: install/logs.md
    - Programmers Manual:
        - Connecting to Middlewares: programmers/connecting-to-middlewares.md
        - Interfaces: programmers/interfaces.md
        - Materialflow: programmers/materialflow.md
        - Entities: programmers/entities.md
    - Glossary: glossary.md
    - Usage: usage.md
    - Deprecated Functionality: deprecated.md
