# This is a basic workflow to help you get started with Actions

name: Lint

on: [pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gitHubActionForPylint:
    name: GitHub Action for pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.3.0
      with:
        python-root-list: "."
        use-pylint: true
        use-pycodestyle: false
        use-flake8: false
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""
