# This is a basic workflow to help you get started with Actions

name: Lint

on: [pull_request]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip3 install pylint  # -r requirements.txt
      - run: pip3 install -r requirements.txt
      - run: pylint **/*.py --fail-under 7
