name: Unit-Tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  orion-setup:
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2

      - name: Run docker-compose
        run: |
          cd test/integration_test
          docker-compose down; docker-compose up -d

  unit-tests:
    needs: orion-setup 
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup Testing
        run: |
          sudo apt -qq update
          sudo apt -qq install -y graphviz
          sudo ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
          pip3 install -r "requirements.txt"
          export PYTHONIOENCODING=utf-8
      - name: Test
        run: |
            python -m xmlrunner discover -s test -v -o ./tmp/build/junit-reports

      - uses: actions/upload-artifact@v2
        with:
          name: Test-Results
          path: tmp/build/junit-reports/*.xml
